### PR TITLE
Micro optimalizations + config changes

### PR DESCRIPTION
**Pull request by Akxe**

### CODE REVIEW

**Comment by Irrelon** [comment]
Hey there! :)

Some of the changes I agree with and some I would like to discuss further. The change to the config files seems to make the application have to do a lot more work to parse the file. Since JS has native JSON interpretation we should have a discussion about the benefits vs extra code.

The beginning lines where each declared variable has been given it's own var statement seems to be a step backwards since (at least my) IDEs complain if using multiple var declarations. This is however one of those more subjective code style things I think... I don't think there is a "correct" way here but I'm relatively sure that a single var executes faster than multiple var statements.

I'm not rejecting anything here by the way, I'd just like to open discussion about the changes so I can understand the motivation and ultimately make the correct decision for the project. :+1:

**Comment by Akxe** [comment]
I was sure you would like the micro optimizations. :)

About the config... my point was, that I had to write `protocol`://`localhost`:`PORT`, even, thought I wanted to redirect to http (thus, it may be more logical to redirect to the same protocol as the call had), localhost for every of my sub pages, with just different port...

I surely don't say my was is better, but I liked the possibility of having the defaults. **And** if we want to make the optimizations a thing, we need to reparse the file anyway... since we should make the routerTable as Map and if you want to make routes as separate class.

**Comment by Irrelon** [comment]
Sorry for not replying sooner, I've been away for a month in Thailand on holiday.

Could you explain a bit more about what you are trying to achieve with defaults? Is it just you want default values for things like url to "localhost" if no url is presented in the config for a particular mapping?

**Comment by Akxe** [comment]
Yes... That is it...

**Pull request closed without merging**
