### PR TITLE
Update and rename config.json to config.cfg

### PR DESCRIPTION
**Pull request by Akxe**
Sorry I don't use github so often... so I struggle with this kind of staff... (sorry for the 2 part pull request)

### CODE REVIEW

**Comment by Irrelon** [comment]
I think a better way of dealing with this would be to support both json and cfg formats, and detect which is specified when the app loads. Switching to a new format that you want to use isn't always going to be well received by others already using the project. I personally prefer the JSON format but am not saying we shouldn't support other formats... just that other formats require a custom parsing system to use whereas JSON is already natively supported.

**Comment by Akxe** [comment]
The thing with the custom format was, that it enabled me to specify, that the same settings apply to multiple host names

**Comment by Irrelon** [comment]
@Akxe That makes a lot of sense and has a lot of utility. I just don't want to force users (including me) to go recreate their configs in a new format so dual format would be very cool :)

**Comment by Akxe** [comment]
True I may redo the parser part while migrating to es6 if you want me to. Or maybe even typescript... but that would require quite a lot...

**Pull request closed without merging**
